# Generated by Django 5.2.9 on 2026-06-01 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('pedagogico', '0004_rename_data_planodeaula_data_prevista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, db_column='escola_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='turma',
            field=models.ForeignKey(blank=True, db_column='turma_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedagogico.turma'),
        ),
        migrations.AlterModelTable(
            name='school',
            table='escolas',
        ),
    ]
