FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Variável PYTHONPATH para encontrar os módulos (heimdall, etc)
ENV PYTHONPATH=/app

EXPOSE 8001

CMD ["uvicorn", "fastapi_service.main:app", "--host", "0.0.0.0", "--port", "8001"]
